apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend-deploy
  namespace: devops
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - devops-frontend
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: frontend
          image: namankali/devops-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: frontend-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: devops-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-service
  namespace: devops
spec:
  selector:
    app: devops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort